routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('product', 'ProductController');
Route::resource('address', 'AddressController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

        public $timestamps = false;
  protected $table = 'products';

    protected $fillable = [
        'title',
        'description',
        'photo',
        'city_id'
    ];

  public  function  Address(){
        return $this->belongsTo('App\Product');

   }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Input;
use App\Product as Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {

        $product = Product::all();

        return response()->json($product);


    }

    public function create(Product $product)
    {
        return response()->json($product);
    }


    public function store(Request $request)
    {

        $request->validate([
            'title' => 'required',
            'city_id' => 'required',

            'description' => 'required',

            'photo' => 'required',


        ]);
//        $product_data = array(
//            'title' => Input::get('title'),
//            'description' => Input::get('description'),
//            'photo' => '',
//            'city_id' => Input::get('city_id'),
//        );
//        if (Input::hasFile('photo')) {
//            $destinationPath = 'uploads';
//            $photo = Input::file('photo');
//            $photo_name = $photo->getClientOriginalName();
//            $photo->move($destinationPath,$photo_name);
//            $product_data['photo'] = $photo_name;
//        }
//        $product_id = Product::insert($product_data);
        $product = Product::create($request->all());

        return response()->json([
            'success' => 'Product has been added',
            'product' => $product            ]);

    }




    public function destroy(Product $product)
    {
        $product->delete();

        return response()->json([
            'success' => 'Product has been deleted Successfully'
        ]);



    }


    public function edit(Product $product)
    {
        return response()->json($product);


    }



    public function update(Request $request,Product $product)
    {

        $request->validate([
            'title' => 'required',
            'city_id' => 'required',

            'description' => 'required',

            'photo' => 'required',
        ]);


//        if (Input::hasFile('photo')) {
//            $destinationPath = 'uploads';
//            $photo = Input::file('photo');
//            $photo_name = $photo->getClientOriginalName();
//            $photo->move($destinationPath,$photo_name);
//            @unlink($destinationPath.'/'.$product->photo);
//        }
//        else
//        {
//            $photo_name=$product->photo;
//        }
//
//        $product_data = array(
//            'title' => Input::get('title'),
//            'description' => Input::get('description'),
//            'photo' => $photo_name,
//            'city_id' => Input::get('city_id'),
//        );
//        $product_id = Product::where('id', '=', $id)->update($product_data);

        $product->update($request->all());

        return response()->json([
            'success' => 'Product has been updated',
            'product' => $product
        ]);
    }
    public function show(Product $product)
    {
        return response()->json($product,200);

    }
}

resources/views/product/create.blade.php
@extends('layouts')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Add Product
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
                <div class="container">

                    <h2>{{ __('product.add_product')  }}</h2>
                    <form role="form" method="post"action="{{route('product.store')}} "   enctype="multipart/form-data" >
                        @method('PATCH')
                        @csrf
                        <div class="form-group">
                            <label for="title">{{ __('product.title')  }}:</label>
                            <input type="text" class="form-control" id="title" name="title">
                        </div>

                        <div class="form-group">
                            <label for="description">{{ __('product.description')  }}:</label>
                            <input type="text" class="form-control" id="description" name="description">
                        </div>

                        <div class="form-group">
                            <label for="photo">{{ __('product.photo')  }}:</label>
                            <input type="file" class="btn btn-primary" id="photo" name="photo">
                        </div>


                        <div class="form-group">
                            <label for="city_id">{{ __('product.city_id')  }}:</label>
                            <input type="number" class="form-control" id="city_id" name="city_id">
                        </div>


                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Edit Product
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif

            {{--<nav class="navbar navbar-inverse">--}}
            {{--<div class="container-fluid">--}}
            {{--<div class="navbar-header">--}}
            {{--<a class="navbar-brand" href="http://crudegenerator.in">Laravel Crud By Crud Generator</a>--}}
            {{--</div>--}}
            {{--<ul class="nav navbar-nav">--}}
            {{--<li><a href="{{route('address')}}">Manage Address</a></li>--}}
            {{--<li><a href="{{route('address.add')}}">Add Address</a></li>--}}
            {{--</ul>--}}
            {{--</div>--}}
            {{--</nav>--}}


                <div class="container">

                    <h2>{{ __('product.update_product')  }}</h2>
                    <form method="post" action="{{ route('product.update', $product->id) }}">
                        @method('PATCH')
                        @csrf
                        <input type="hidden" value="<?php echo $product->id ?>"   name="product_id">

                        <div class="form-group">
                            <label for="title">{{ __('product.title')  }}:</label>
                            <input type="text" value="<?php echo $product->title ?>" class="form-control" id="title" name="title">
                        </div>

                        <div class="form-group">
                            <label for="description">{{ __('product.description')  }}:</label>
                            <input type="text" value="<?php echo $product->description ?>" class="form-control" id="description" name="description">
                        </div>

                        <div class="form-group">
                            <label for="photo">{{ __('product.photo')  }}:</label>
                            <input type="file"  class="btn btn-primary" id="photo" name="photo">
                        </div>

                        <div class="form-group">
                            <label for="city_id">{{ __('product.city_id')  }}:</label>
                            <input type="number" value="<?php echo $product->city_id ?>" class="form-control" id="city_id" name="city_id">
                        </div>


                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="uper">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div><br />
        @endif

            {{--<nav class="navbar navbar-inverse">--}}
                {{--<div class="container-fluid">--}}
                    {{--<div class="navbar-header">--}}
                        {{--<a class="navbar-brand" href="http://crudegenerator.in">Laravel Crud By Noor</a>--}}
                    {{--</div>--}}
                    {{--<ul class="nav navbar-nav">--}}
                        {{--<li class="active" ><a href="{{route('product')}}">{{ __('product.manage_product')  }}</a></li>--}}
                        {{--<li><a href="{{route('product.add')}}">{{ __('product.add-product')  }}</a></li>--}}
                    {{--</ul>--}}
                {{--</div>--}}
            {{--</nav>--}}


            <div class="container">

                <h2>{{ __('product.manage_product')  }}</h2>



                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('product.id')  }}</th>

                            <th>{{ __('product.title')  }}</th>
                            <th>{{ __('product.description')  }}</th>
                            <th>{{ __('product.photo')  }}</th>
                            <th>{{ __('product.city_id')  }}</th>
                            <th>{{ __('product.actions')  }}</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($product as $product)
                            <tr>
                                <td>{{$product->id}} </td>
                                <td>{{$product->title}} </td>
                                <td>{{$product->description}} </td>
                                <td> <img src="uploads/{{$product->photo}}" > </td>
                                <td>{{$product->city_id}} </td>



                                <td><a href="{{ route('product.edit',$product->id)}}" class="btn btn-primary">Edit</a>

                                    <form action="{{ route('product.destroy', $product->id)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                                </td>


                            </tr>

                        @endforeach
                        </tbody>
                    </table>

            </div>

@endsection