routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('product', 'ProductController');
Route::resource('address', 'AddressController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/AddressController.php
<?php namespace App\Http\Controllers;

use App\Address as Address;
use Illuminate\Http\Request;

use Hash;

class AddressController extends Controller
{

    public function index()
        {

            $address = Address::all();
            return response()->json($address);

        }

    public function create(Address $address)
        {
            return response()->json($address);
        }

    public function store(Request $request)


        {


            $request->validate([
                'city' => 'required',

            ]);

            $address = Address::create($request->get('city'));

            return response()->json([
                'success' => 'Address has been added',
                'address' => $address
            ]);



        }


    public function destroy(Address $address)
        {

            //return response()->json($address->delete(),204);

            $address->delete();

            return response()->json([
                'success' => 'address has been deleted Successfully'
            ]);
//            $address = Address::find($id);
//            $address->delete();
//
//            return redirect('/address')->with('success', 'address has been deleted Successfully');
        }

    public function edit(Address $address)
        {

            return response($address);


//            $address = Address::find($id);
//
//            return view('address.edit', compact('address'));
        }



    public function update(Request $request,Address $address)
        {
            $request->validate([
                'city' => 'required',
            ]);

            $address->update($request->all());

            return response()->json([
                'success' => 'Address has been updated',
                'address' => $address
            ]);



        }
    public function show(Address $address)
    {
        //
        return response()->json($address,200);


    }

}

resources/views/address/create.blade.php
                @extends('layouts')

                @section('content')
                    <style>
                        .uper {
                            margin-top: 40px;
                        }
                    </style>
                    <div class="card uper">
                        <div class="card-header">
                            Add Product
                        </div>
                        <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div><br />
                            @endif
                            <form method="post" action="{{ route('address.store') }}">
                                <div class="form-group">
                                    @csrf

                                <div class="form-group">
                                    <label for="city">City:</label>
                                    <input type="text" class="form-control" name="city"/>
                                </div>
                                <button type="submit" class="btn btn-primary">Add</button>
                                </div>
                            </form>


                    </div>
@endsection

resources/views/address/edit.blade.php
                @extends('layouts')

                @section('content')
                    <style>
                        .uper {
                            margin-top: 40px;
                        }
                    </style>
                    <div class="card uper">
                        <div class="card-header">
                            Edit Product
                        </div>
                        <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div><br />
                            @endif

                                {{--<nav class="navbar navbar-inverse">--}}
                                {{--<div class="container-fluid">--}}
                                {{--<div class="navbar-header">--}}
                                {{--<a class="navbar-brand" href="http://crudegenerator.in">Laravel Crud By Crud Generator</a>--}}
                                {{--</div>--}}
                                {{--<ul class="nav navbar-nav">--}}
                                {{--<li><a href="{{route('address')}}">Manage Address</a></li>--}}
                                {{--<li><a href="{{route('address.add')}}">Add Address</a></li>--}}
                                {{--</ul>--}}
                                {{--</div>--}}
                                {{--</nav>--}}

                                <form method="post" action="{{ route('address.update', $address->id) }}">
                                @method('PATCH')
                                @csrf
                                <div class="form-group">
                                    <label for="city">City:</label>
                                    <input type="text" class="form-control" name="city" value={{ $address->city }} />
                                </div>

                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
@endsection

resources/views/address/index.blade.php
@extends('layouts')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="uper">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div><br />
        @endif
{{--<nav class="navbar navbar-inverse">--}}
    {{--<div class="container-fluid">--}}
        {{--<div class="navbar-header">--}}
            {{--<a class="navbar-brand" href="http://crudegenerator.in">Laravel Crud By Crud Generator</a>--}}
        {{--</div>--}}
        {{--<ul class="nav navbar-nav">--}}
            {{--<li class="active" ><a href="{{route('address')}}">Manage Address</a></li>--}}
            {{--<li><a href="{{route('address.add')}}">Add Address</a></li>--}}
        {{--</ul>--}}
    {{--</div>--}}
{{--</nav>--}}


    <h2>{{ __('address.manage_address')  }}</h2>



            <table class="table table-striped">
                <thead>
                <tr>
                    <th>{{ __('address.id')  }}</th>
                    <th>{{ __('address.city')  }}</th>
                    <th>{{ __('address.actions')  }}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($address as $address)
                    <tr>
                        <td>{{$address->id}}</td>
                        <td>{{$address->city}}</td>

                        <td><a href="{{ route('address.edit',$address->id)}}" class="btn btn-primary">Edit</a></td>
                        <td>
                            <form action="{{ route('address.destroy', $address->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div>
@endsection